### ISSUE TITLE
is it possible to release this project on pypi?

### ISSUE THREAD

**Issue by Trim21** [scauligi/refried#1]
I want use this project, but git submodule is much more difficult to use than pip as fetching a python package.

It would be very nice to have a pypi release instead of simple cloning it and put it in my git repo.

**Comment by Trim21** [comment]
I'd like to create a pull request, but I don't know do you use [poetry](http://python-poetry.org/)...

**Comment by scauligi** [comment]
Thanks for the tip! I've migrated the repository to a proper package, it should now be published on PyPI as "beancount-refried".

**Comment by Trim21** [comment]
there is no need to keep `PKG-INFO` and `setup.py` in your repo as you are using poetry.

**Comment by scauligi** [comment]
I'm keeping these in there to support "development" installs (i.e., running `pip install -e .` from the repo directory), particularly for people who may not have poetry installed.

Is there a better way of doing this?

**Comment by Trim21** [comment]
Oh, I missed it. It seems this is the only way.

**Comment by Trim21** [comment]
would you mind downgrade your required python version and make a new release? It seem that `^3.8` is a little bit high.

**Comment by scauligi** [comment]
I've reduced the python requirement to 3.6, but I haven't tested it. You may need to file additional issues/PRs if I've used any 3.7/3.8isms.

That being said, I have been making use of the (incredibly useful) [3.8 assignment expressions](https://www.python.org/dev/peps/pep-0572/) in some scripts and plugins that I have yet to incorporate into refried; at the point that I include them I would have to bump the python version back up to 3.8.
